// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDmAoX1tjLIllIuaO7wGdyIhjV8gpLCTNk",
    authDomain: "lactoview4.firebaseapp.com",
    projectId: "lactoview4",
    storageBucket: "lactoview4.firebasestorage.app",
    messagingSenderId: "386045070193",
    appId: "1:386045070193:web:92ed68e837498f509a04d0",
  );

  //Atualizar o dados abaixo >>>

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDmAoX1tjLIllIuaO7wGdyIhjV8gpLCTNk",
    authDomain: "lactoview4.firebaseapp.com",
    projectId: "lactoview4",
    storageBucket: "lactoview4.firebasestorage.app",
    messagingSenderId: "386045070193",
    appId: "1:386045070193:web:92ed68e837498f509a04d0",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyDmAoX1tjLIllIuaO7wGdyIhjV8gpLCTNk",
    authDomain: "lactoview4.firebaseapp.com",
    projectId: "lactoview4",
    storageBucket: "lactoview4.firebasestorage.app",
    messagingSenderId: "386045070193",
    appId: "1:386045070193:web:92ed68e837498f509a04d0",
  );

  static const FirebaseOptions macos = FirebaseOptions(
  apiKey: "AIzaSyDmAoX1tjLIllIuaO7wGdyIhjV8gpLCTNk",
    authDomain: "lactoview4.firebaseapp.com",
    projectId: "lactoview4",
    storageBucket: "lactoview4.firebasestorage.app",
    messagingSenderId: "386045070193",
    appId: "1:386045070193:web:92ed68e837498f509a04d0",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyDmAoX1tjLIllIuaO7wGdyIhjV8gpLCTNk",
    authDomain: "lactoview4.firebaseapp.com",
    projectId: "lactoview4",
    storageBucket: "lactoview4.firebasestorage.app",
    messagingSenderId: "386045070193",
    appId: "1:386045070193:web:92ed68e837498f509a04d0",
  );
}
